# Generated by Django 5.2.7 on 2025-10-23 06:59

from django.db import migrations, models


def drop_guest_memberships(apps, schema_editor):
    ServiceMembership = apps.get_model("accounts", "ServiceMembership")
    ServiceMembership.objects.filter(role="GUEST").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_move_availability_models"),
    ]

    operations = [
        migrations.RunPython(drop_guest_memberships, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="servicemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("OFFICE_MANAGER", "Office Manager"),
                    ("GUIDE", "Guide"),
                ],
                max_length=20,
            ),
        ),
    ]
