# Generated by Django 5.2.7 on 2025-10-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_servicemembership_accepted_at_and_more'),
        ('orgs', '0003_guideservice_logo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceinvitation',
            unique_together={('guide_service', 'email')},
        ),
    ]
