# Generated by Django 5.2.7 on 2025-10-29 06:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0009_remove_trip_price_cents'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('medical_notes', models.TextField(blank=True)),
                ('dietary_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'email'],
            },
        ),
        migrations.CreateModel(
            name='TripParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_size', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('info_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete')], default='PENDING', max_length=12)),
                ('waiver_status', models.CharField(choices=[('PENDING', 'Pending'), ('SIGNED', 'Signed')], default='PENDING', max_length=12)),
                ('last_guest_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_parties', to='bookings.guestprofile')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='trips.trip')),
            ],
            options={
                'ordering': ['trip__start', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuestAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('purpose', models.CharField(choices=[('link', 'General access link')], default='link', max_length=20)),
                ('single_use', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='bookings.guestprofile')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='bookings.tripparty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripPartyGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_guests', to='bookings.guestprofile')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_guests', to='bookings.tripparty')),
            ],
            options={
                'unique_together': {('party', 'guest')},
            },
        ),
        migrations.AddField(
            model_name='tripparty',
            name='guests',
            field=models.ManyToManyField(related_name='parties', through='bookings.TripPartyGuest', to='bookings.guestprofile'),
        ),
    ]
