# Generated by Django 5.2.7 on 2025-10-20 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiver', to='bookings.booking')),
            ],
        ),
    ]
