services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    env_file: ../.env
    depends_on: [postgres]
    ports: ["8000:8000"]
    volumes:
      - ../backend:/app

  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.frontend
    ports: ["5173:5173"]
    environment:
      VITE_API_URL: http://backend:8000
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules
    command: >
      sh -c "pnpm install --prefer-offline --force --reporter=append-only && pnpm dev --host"

  playwright:
    image: mcr.microsoft.com/playwright:v1.47.2-focal
    working_dir: /app/frontend
    command: tail -f /dev/null
    depends_on:
      - backend
      - frontend
    environment:
      PLAYWRIGHT_BASE_URL: http://frontend:5173
      BASE_URL: http://frontend:5173
    volumes:
      - ..:/app

volumes:
  pgdata:
  frontend_node_modules:
