FROM node:20-slim
WORKDIR /app
COPY frontend/package.json /app/package.json
RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install
COPY frontend/ /app/
CMD ["pnpm", "dev", "--host"]
