# Generated by Django 5.2.7 on 2025-10-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        ('accounts', '0002_guideavailability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
