# Generated by Django 5.2.7 on 2025-10-24 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_guideservice_logo'),
        ('trips', '0004_pricingmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingmodel',
            options={'ordering': ('name', 'id')},
        ),
        migrations.AlterModelOptions(
            name='pricingtier',
            options={'ordering': ('min_guests',)},
        ),
        migrations.AddField(
            model_name='trip',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pricing_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trips.pricingmodel'),
        ),
        migrations.AddField(
            model_name='trip',
            name='pricing_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='target_client_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='target_guide_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='template_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TripTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration_hours', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('target_client_count', models.PositiveIntegerField(default=1)),
                ('target_guide_count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trip_templates', to=settings.AUTH_USER_MODEL)),
                ('pricing_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_templates', to='trips.pricingmodel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_templates', to='orgs.guideservice')),
            ],
            options={
                'ordering': ('title', 'id'),
                'unique_together': {('service', 'title')},
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trips.triptemplate'),
        ),
    ]
