# Generated by Django 5.2.7 on 2025-10-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_pricingmodel_options_alter_pricingtier_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='capacity',
        ),
    ]
