# Generated by Django 5.2.7 on 2025-10-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_remove_trip_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='pricing_model',
        ),
        migrations.RemoveField(
            model_name='triptemplate',
            name='pricing_model',
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='deposit_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='is_deposit_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='pricing_currency',
            field=models.CharField(default='usd', max_length=10),
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='pricing_tiers',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='PricingModel',
        ),
        migrations.DeleteModel(
            name='PricingTier',
        ),
    ]
