# Generated by Django 5.2.7 on 2025-10-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_checkout_session',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
